[package]
name = "ferrugem-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
fake = "3.0.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
