services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DEVICE_COUNT=3000
      - PORT=8080
    network_mode: host

  api02:
    <<: *api
    environment:
      - DEVICE_COUNT=3000
      - PORT=8081
    hostname: api02
  
  api03:
    <<: *api
    environment:
      - DEVICE_COUNT=3000
      - PORT=8082
    hostname: api02

  api04:
    <<: *api
    environment:
      - DEVICE_COUNT=3000
      - PORT=8083
    hostname: api02

  api05:
    <<: *api
    environment:
      - DEVICE_COUNT=3000
      - PORT=8084
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - api03
      - api04
      - api05
    network_mode: host