services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DEVICE_COUNT=500
      - PORT=8080
    network_mode: host

  api02:
    <<: *api
    environment:
      - DEVICE_COUNT=500
      - PORT=8081
    hostname: api02
  
  api03:
    <<: *api
    environment:
      - DEVICE_COUNT=500
      - PORT=8082
    hostname: api02

  api04:
    <<: *api
    environment:
      - DEVICE_COUNT=500
      - PORT=8083
    hostname: api02

  api05:
    <<: *api
    environment:
      - DEVICE_COUNT=500
      - PORT=8084
    hostname: api02

  ferrugem:
    image: erickcestari/ferrugem:latest
    volumes:
      - ./ferrugem.toml:/usr/local/bin/ferrugem.toml
    depends_on:
      - api01
      - api02
      - api03
      - api04
      - api05
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536